import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { isAbsolute, join, resolve } from "node:path";
import { run } from "./exec.ts";
import { CliError, log } from "./log.ts";
import { appName, type AdapterRef, type Manifest } from "./manifest.ts";

// Static composition (docs/design.md): generate a per-app SwiftPM host that depends on
// EngawaHostCore (built-ins + the contract-coupled update adapter) plus exactly the adapters
// this app declared, build it, and return the host binary path. sqlite is compiled in only when
// the app asks for it — never baked into every host.
export async function buildHost(home: string, appDir: string, manifest: Manifest, config: "debug" | "release"): Promise<string> {
  if (process.platform === "win32") return buildWindowsHost(home, manifest);

  const hostDir = join(appDir, "build", ".host");
  const sources = join(hostDir, "Sources", "EngawaHost");
  mkdirSync(sources, { recursive: true });

  writeFileSync(join(hostDir, "Package.swift"), packageSwift(home, appDir, manifest));
  writeFileSync(join(sources, "main.swift"), mainSwift(manifest));

  log.step(`building host (${config})${manifest.adapters.length > 0 ? ` with ${manifest.adapters.map((a) => a.package).join(", ")}` : " (core only)"}`);
  await run("swift", ["build", "--package-path", hostDir, "-c", config]);
  const binary = join(hostDir, ".build", config, "EngawaHost");
  if (!existsSync(binary)) throw new CliError(`host binary not found at ${binary}`);
  return binary;
}

// The Windows reference host (hosts/windows) composes statically via CMake, not SwiftPM. It builds
// one EngawaHost.exe that includes the built-ins plus the reference sqlite + update adapters. Per-app
// adapter selection is not yet wired on Windows, so an app that declares other adapters is warned
// that the CMake build will not add them.
async function buildWindowsHost(home: string, manifest: Manifest): Promise<string> {
  const scriptDir = join(home, "hosts", "windows");
  log.step("building host (windows) via CMake");
  await run("powershell", ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", join(scriptDir, "build.ps1")]);
  const binary = join(scriptDir, "build", "EngawaHost.exe");
  if (!existsSync(binary)) throw new CliError(`host binary not found at ${binary}`);
  const extra = manifest.adapters.filter((a) => a.package.toLowerCase() !== "sqlite");
  if (extra.length > 0) {
    log.warn(`windows host bundles sqlite + update statically; declared adapter(s) ${extra.map((a) => a.package).join(", ")} are not compiled in yet (per-app composition is macOS-only for now)`);
  }
  return binary;
}

function adapterPackagePath(appDir: string, ref: AdapterRef): string {
  return isAbsolute(ref.path!) ? ref.path! : resolve(appDir, ref.path!);
}

function packageSwift(home: string, appDir: string, manifest: Manifest): string {
  const deps = [
    `.package(path: ${swiftString(join(home, "hosts", "macos"))})`,
    `.package(path: ${swiftString(join(home, "hosts", "macos-kit"))})`,
    ...manifest.adapters.map((a) =>
      a.path !== undefined
        ? `.package(path: ${swiftString(adapterPackagePath(appDir, a))})`
        : `.package(url: ${swiftString(a.url!)}, revision: ${swiftString(a.revision!)})`,
    ),
  ];
  const products = [
    `.product(name: "EngawaHostCore", package: "macos")`,
    `.product(name: "EngawaKit", package: "macos-kit")`,
    ...manifest.adapters.map((a) => `.product(name: ${swiftString(a.product)}, package: ${swiftString(a.package)})`),
  ];
  return `// swift-tools-version:6.0
// Generated by \`engawa\` — a per-app host composition. Do not edit.
import PackageDescription

let package = Package(
    name: ${swiftString(`${appName(manifest)}Host`)},
    platforms: [.macOS(.v13)],
    dependencies: [
        ${deps.join(",\n        ")},
    ],
    targets: [
        .executableTarget(
            name: "EngawaHost",
            dependencies: [
                ${products.join(",\n                ")},
            ],
            path: "Sources/EngawaHost"
        )
    ]
)
`;
}

function mainSwift(manifest: Manifest): string {
  const imports = ["import EngawaHostCore", "import EngawaKit", ...manifest.adapters.map((a) => `import ${a.product}`)];
  const registrations = manifest.adapters.map((a) => a.register).join(", ");
  return `${imports.join("\n")}

// Generated by \`engawa\`. The app's declared adapters, statically composed into the host.
EngawaRuntime.run(appAdapters: [${registrations}])
`;
}

// Swift string literal. Paths/URLs may contain backslashes or quotes; escape them.
function swiftString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
