import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { isAbsolute, join, resolve } from "node:path";
import { run } from "./exec.ts";
import { CliError, log } from "./log.ts";
import { appName, type AdapterRef, type Manifest } from "./manifest.ts";

// Static composition (docs/design.md): generate a per-app SwiftPM host that depends on
// EngawaHostCore (built-ins + the contract-coupled update adapter) plus exactly the adapters
// this app declared, build it, and return the host binary path. sqlite is compiled in only when
// the app asks for it — never baked into every host.
export async function buildHost(home: string, appDir: string, manifest: Manifest, config: "debug" | "release", trustRoot?: string): Promise<string> {
  if (process.platform === "win32") return buildWindowsHost(home, appDir, manifest, config, trustRoot);

  const hostDir = join(appDir, "build", ".host");
  const sources = join(hostDir, "Sources", "EngawaHost");
  mkdirSync(sources, { recursive: true });

  writeFileSync(join(hostDir, "Package.swift"), packageSwift(home, appDir, manifest));
  writeFileSync(join(sources, "main.swift"), mainSwift(manifest));

  log.step(`building host (${config})${manifest.adapters.length > 0 ? ` with ${manifest.adapters.map((a) => a.package).join(", ")}` : " (core only)"}`);
  await run("swift", ["build", "--package-path", hostDir, "-c", config]);
  const binary = join(hostDir, ".build", config, "EngawaHost");
  if (!existsSync(binary)) throw new CliError(`host binary not found at ${binary}`);
  return binary;
}

// The Windows host composes statically via CMake, not SwiftPM. Generate a per-app CMakeLists (via
// hosts/windows/engawa-host.cmake) + a compose TU that registers exactly this app's declared adapters
// (a local path, or a git url+revision fetched by FetchContent), then build it. Mirrors the macOS
// per-app SwiftPM host: sqlite is compiled in only when the app declares it.
interface WinAdapter { factory: string; localDir?: string; url?: string; revision?: string; pkg: string }

async function buildWindowsHost(home: string, appDir: string, manifest: Manifest, config: "debug" | "release", trustRoot?: string): Promise<string> {
  const hostDir = join(appDir, "build", ".host-win");
  const buildDir = join(hostDir, "build");
  mkdirSync(hostDir, { recursive: true });

  const adapters: WinAdapter[] = manifest.adapters.map((a): WinAdapter => {
    const factory = cppFactory(a.package);
    if (a.path !== undefined) {
      const dir = join(resolve(appDir, a.path), "hosts", "windows");
      if (!existsSync(dir)) throw new CliError(`adapter "${a.package}" has no Windows implementation at ${dir}`);
      return { factory, localDir: dir, pkg: a.package };
    }
    return { factory, url: a.url!, revision: a.revision!, pkg: a.package };
  });

  writeFileSync(join(hostDir, "compose.cpp"), composeCpp(adapters, trustRoot));
  writeFileSync(join(hostDir, "CMakeLists.txt"), winCmakeLists(home, hostDir, adapters));

  log.step(`building host (windows, ${config})${adapters.length > 0 ? ` with ${adapters.map((a) => a.pkg).join(", ")}` : " (core only)"}`);
  await run("powershell", [
    "-NoProfile", "-ExecutionPolicy", "Bypass",
    "-File", join(home, "hosts", "windows", "cmake-build.ps1"),
    "-Source", hostDir, "-Build", buildDir,
  ]);
  const binary = join(buildDir, "EngawaHost.exe");
  if (!existsSync(binary)) throw new CliError(`host binary not found at ${binary}`);
  return binary;
}

// Windows adapter factory convention (docs/design.md "Composition"): each adapter's hosts/windows/*.cpp
// defines a free function make<Pascal(package)>Adapter() returning std::unique_ptr<IAdapter>.
function cppFactory(pkg: string): string {
  const pascal = pkg.split(/[^A-Za-z0-9]+/).filter(Boolean).map((s) => s[0]!.toUpperCase() + s.slice(1)).join("");
  return `make${pascal}Adapter`;
}

// CMake wants forward slashes even on Windows.
function cmakePath(p: string): string {
  return p.replace(/\\/g, "/");
}

// The generated compose TU: forward-declare each adapter's factory and register it (§3 static
// composition), and compile in the app's update trust root (§7.1). Replaces the default
// hosts/windows/src/Compose.cpp for this app. Exported for unit testing (cli/test/compose.test.ts).
export function composeCpp(adapters: WinAdapter[], trustRoot?: string): string {
  return (
    `// Generated by \`engawa\` — the app's declared adapters + baked trust root. Do not edit.\n` +
    `#include "Compose.hpp"\n#include "Adapter.hpp"\n#include <memory>\n#include <string>\n\n` +
    adapters.map((a) => `std::unique_ptr<IAdapter> ${a.factory}();\n`).join("") +
    `\nvoid registerAppAdapters(Dispatcher& dispatcher, IEventEmitter* emitter) {\n` +
    adapters.map((a) => `  dispatcher.registerAdapter(${a.factory}(), emitter);\n`).join("") +
    `}\n\n` +
    // §7.1: compile the trust root in so it can't be swapped by editing a file beside the exe. base64
    // is safe in a C string literal (no quotes/backslashes); assert that before embedding.
    `std::string bakedTrustRoot() { return ${cppStringLiteral(trustRoot ?? "")}; }\n`
  );
}

// A C++ string literal for a base64 trust root. base64's alphabet ([A-Za-z0-9+/=]) contains no
// characters needing escaping; reject anything else rather than emit a malformed or unsafe literal.
function cppStringLiteral(s: string): string {
  if (s !== "" && !/^[A-Za-z0-9+/=]+$/.test(s)) throw new CliError(`trust root is not base64: ${s}`);
  return `"${s}"`;
}

function winCmakeLists(home: string, hostDir: string, adapters: WinAdapter[]): string {
  const git = adapters.filter((a) => a.url !== undefined);
  const adapterDirs = adapters.map((a) =>
    a.localDir !== undefined ? `"${cmakePath(a.localDir)}"` : `"\${${a.pkg}_SOURCE_DIR}/hosts/windows"`,
  );
  return `# Generated by \`engawa\` — a per-app Windows host composition. Do not edit.
cmake_minimum_required(VERSION 3.20)
cmake_policy(SET CMP0091 NEW)
project(EngawaHost LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

include("${cmakePath(join(home, "hosts", "windows", "engawa-host.cmake"))}")
${git.length > 0 ? "include(FetchContent)\n" + git.map((g) =>
  `FetchContent_Declare(${g.pkg} GIT_REPOSITORY "${g.url}" GIT_TAG "${g.revision}")\nFetchContent_MakeAvailable(${g.pkg})`).join("\n") + "\n" : ""}
engawa_add_host(EngawaHost
  ADAPTERS ${adapterDirs.join("\n           ")}
  COMPOSE  "${cmakePath(join(hostDir, "compose.cpp"))}")
`;
}

function adapterPackagePath(appDir: string, ref: AdapterRef): string {
  return isAbsolute(ref.path!) ? ref.path! : resolve(appDir, ref.path!);
}

function packageSwift(home: string, appDir: string, manifest: Manifest): string {
  const deps = [
    `.package(path: ${swiftString(join(home, "hosts", "macos"))})`,
    `.package(path: ${swiftString(join(home, "hosts", "macos-kit"))})`,
    ...manifest.adapters.map((a) =>
      a.path !== undefined
        ? `.package(path: ${swiftString(adapterPackagePath(appDir, a))})`
        : `.package(url: ${swiftString(a.url!)}, revision: ${swiftString(a.revision!)})`,
    ),
  ];
  const products = [
    `.product(name: "EngawaHostCore", package: "macos")`,
    `.product(name: "EngawaKit", package: "macos-kit")`,
    ...manifest.adapters.map((a) => `.product(name: ${swiftString(a.product)}, package: ${swiftString(a.package)})`),
  ];
  return `// swift-tools-version:6.0
// Generated by \`engawa\` — a per-app host composition. Do not edit.
import PackageDescription

let package = Package(
    name: ${swiftString(`${appName(manifest)}Host`)},
    platforms: [.macOS(.v13)],
    dependencies: [
        ${deps.join(",\n        ")},
    ],
    targets: [
        .executableTarget(
            name: "EngawaHost",
            dependencies: [
                ${products.join(",\n                ")},
            ],
            path: "Sources/EngawaHost"
        )
    ]
)
`;
}

function mainSwift(manifest: Manifest): string {
  const imports = ["import EngawaHostCore", "import EngawaKit", ...manifest.adapters.map((a) => `import ${a.product}`)];
  const registrations = manifest.adapters.map((a) => a.register).join(", ");
  return `${imports.join("\n")}

// Generated by \`engawa\`. The app's declared adapters, statically composed into the host.
EngawaRuntime.run(appAdapters: [${registrations}])
`;
}

// Swift string literal. Paths/URLs may contain backslashes or quotes; escape them.
function swiftString(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}
